# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OXY.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OXY(object):
    def setupUi(self, OXY):
        OXY.setObjectName("OXY")
        OXY.resize(865, 581)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        OXY.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/eye.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        OXY.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(OXY)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(560, 0, 301, 241))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(560, 260, 301, 261))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-10, -250, 341, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox.setGeometry(QtCore.QRect(100, 10, 69, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setUnderline(False)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.textEdit = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit.setGeometry(QtCore.QRect(180, 10, 171, 31))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(360, 10, 75, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.comboBox_name = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_name.setGeometry(QtCore.QRect(40, 50, 51, 22))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.comboBox_name.setFont(font)
        self.comboBox_name.setMaxVisibleItems(6)
        self.comboBox_name.setObjectName("comboBox_name")
        self.comboBox_name.addItem("")
        self.comboBox_name.addItem("")
        self.comboBox_name.addItem("")
        self.comboBox_sex = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_sex.setGeometry(QtCore.QRect(90, 50, 51, 22))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.comboBox_sex.setFont(font)
        self.comboBox_sex.setMaxVisibleItems(6)
        self.comboBox_sex.setObjectName("comboBox_sex")
        self.comboBox_sex.addItem("")
        self.comboBox_sex.addItem("")
        self.comboBox_sex.addItem("")
        self.comboBox_age = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_age.setGeometry(QtCore.QRect(140, 50, 51, 22))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.comboBox_age.setFont(font)
        self.comboBox_age.setMaxVisibleItems(6)
        self.comboBox_age.setObjectName("comboBox_age")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_hosID = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_hosID.setGeometry(QtCore.QRect(330, 50, 61, 22))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.comboBox_hosID.setFont(font)
        self.comboBox_hosID.setMaxVisibleItems(6)
        self.comboBox_hosID.setObjectName("comboBox_hosID")
        self.comboBox_hosID.addItem("")
        self.comboBox_hosID.addItem("")
        self.comboBox_hosID.addItem("")
        self.comboBox_docMain = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_docMain.setGeometry(QtCore.QRect(190, 50, 71, 22))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.comboBox_docMain.setFont(font)
        self.comboBox_docMain.setMaxVisibleItems(6)
        self.comboBox_docMain.setObjectName("comboBox_docMain")
        self.comboBox_docMain.addItem("")
        self.comboBox_docMain.addItem("")
        self.comboBox_docMain.addItem("")
        self.comboBox_docMain.addItem("")
        self.comboBox_id_2 = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_id_2.setGeometry(QtCore.QRect(390, 50, 71, 22))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBox_id_2.setFont(font)
        self.comboBox_id_2.setMaxVisibleItems(6)
        self.comboBox_id_2.setObjectName("comboBox_id_2")
        self.comboBox_id_2.addItem("")
        self.comboBox_id_2.addItem("")
        self.comboBox_id_2.addItem("")
        self.comboBox_docMain_2 = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_docMain_2.setGeometry(QtCore.QRect(260, 50, 71, 22))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.comboBox_docMain_2.setFont(font)
        self.comboBox_docMain_2.setMaxVisibleItems(6)
        self.comboBox_docMain_2.setObjectName("comboBox_docMain_2")
        self.comboBox_docMain_2.addItem("")
        self.comboBox_docMain_2.addItem("")
        self.comboBox_docMain_2.addItem("")
        self.comboBox_docMain_2.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 50, 75, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralWidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 80, 541, 439))
        self.tableWidget.setMinimumSize(QtCore.QSize(519, 439))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.tableWidget.setFont(font)
        self.tableWidget.setToolTip("")
        self.tableWidget.setAutoScrollMargin(10)
        self.tableWidget.setDragEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(14)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(6)
        item.setFont(font)
        self.tableWidget.setItem(0, 0, item)
        OXY.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(OXY)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 865, 23))
        self.menuBar.setObjectName("menuBar")
        self.file = QtWidgets.QMenu(self.menuBar)
        self.file.setObjectName("file")
        self.edit = QtWidgets.QMenu(self.menuBar)
        self.edit.setObjectName("edit")
        self.window = QtWidgets.QMenu(self.menuBar)
        self.window.setObjectName("window")
        self.setting = QtWidgets.QMenu(self.menuBar)
        self.setting.setObjectName("setting")
        self.about = QtWidgets.QMenu(self.menuBar)
        self.about.setObjectName("about")
        self.serach = QtWidgets.QMenu(self.menuBar)
        self.serach.setObjectName("serach")
        OXY.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(OXY)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setAutoFillBackground(True)
        self.toolBar.setObjectName("toolBar")
        OXY.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_user = QtWidgets.QToolBar(OXY)
        self.toolBar_user.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.toolBar_user.setObjectName("toolBar_user")
        OXY.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_user)
        self.actionNew = QtWidgets.QAction(OXY)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.actionNew.setFont(font)
        self.actionNew.setObjectName("actionNew")
        self.actionImage = QtWidgets.QAction(OXY)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.actionImage.setFont(font)
        self.actionImage.setObjectName("actionImage")
        self.actionnew_Window = QtWidgets.QAction(OXY)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.actionnew_Window.setFont(font)
        self.actionnew_Window.setObjectName("actionnew_Window")
        self.actionFont = QtWidgets.QAction(OXY)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.actionFont.setFont(font)
        self.actionFont.setObjectName("actionFont")
        self.actionStyle = QtWidgets.QAction(OXY)
        self.actionStyle.setObjectName("actionStyle")
        self.actionOpen = QtWidgets.QAction(OXY)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(OXY)
        self.actionSave.setObjectName("actionSave")
        self.actionBaidu = QtWidgets.QAction(OXY)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.actionBaidu.setFont(font)
        self.actionBaidu.setObjectName("actionBaidu")
        self.actionAbout = QtWidgets.QAction(OXY)
        self.actionAbout.setObjectName("actionAbout")
        self.actionData_Update = QtWidgets.QAction(OXY)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/database_update.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionData_Update.setIcon(icon1)
        self.actionData_Update.setObjectName("actionData_Update")
        self.actionMagnifying = QtWidgets.QAction(OXY)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/magnifying.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMagnifying.setIcon(icon2)
        self.actionMagnifying.setObjectName("actionMagnifying")
        self.actionReduce = QtWidgets.QAction(OXY)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/reduce.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReduce.setIcon(icon3)
        self.actionReduce.setObjectName("actionReduce")
        self.actionDatabase_Download = QtWidgets.QAction(OXY)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/database_download.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDatabase_Download.setIcon(icon4)
        self.actionDatabase_Download.setObjectName("actionDatabase_Download")
        self.actionWarning_Black = QtWidgets.QAction(OXY)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/warning_Black.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWarning_Black.setIcon(icon5)
        self.actionWarning_Black.setObjectName("actionWarning_Black")
        self.actionWarning_Red = QtWidgets.QAction(OXY)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/warning_Red.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWarning_Red.setIcon(icon6)
        self.actionWarning_Red.setObjectName("actionWarning_Red")
        self.actionBack = QtWidgets.QAction(OXY)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/back.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBack.setIcon(icon7)
        self.actionBack.setObjectName("actionBack")
        self.actionGo = QtWidgets.QAction(OXY)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/go.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGo.setIcon(icon8)
        self.actionGo.setObjectName("actionGo")
        self.actionPatient = QtWidgets.QAction(OXY)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/patient.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap("icons/patient.icns"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPatient.setIcon(icon9)
        self.actionPatient.setShortcutContext(QtCore.Qt.WidgetShortcut)
        self.actionPatient.setObjectName("actionPatient")
        self.actionDoctor = QtWidgets.QAction(OXY)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/doctor.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon10.addPixmap(QtGui.QPixmap("icons/doctor.icns"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionDoctor.setIcon(icon10)
        self.actionDoctor.setObjectName("actionDoctor")
        self.actionAddRow = QtWidgets.QAction(OXY)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/addRow.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddRow.setIcon(icon11)
        self.actionAddRow.setObjectName("actionAddRow")
        self.actionDeleteRow = QtWidgets.QAction(OXY)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/deleteRow.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeleteRow.setIcon(icon12)
        self.actionDeleteRow.setObjectName("actionDeleteRow")
        self.actionHome = QtWidgets.QAction(OXY)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icons/home.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHome.setIcon(icon13)
        self.actionHome.setObjectName("actionHome")
        self.actionMianIcon = QtWidgets.QAction(OXY)
        self.actionMianIcon.setCheckable(True)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/main/eye.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMianIcon.setIcon(icon14)
        self.actionMianIcon.setObjectName("actionMianIcon")
        self.file.addAction(self.actionNew)
        self.file.addAction(self.actionOpen)
        self.file.addAction(self.actionSave)
        self.edit.addAction(self.actionImage)
        self.window.addAction(self.actionnew_Window)
        self.setting.addAction(self.actionFont)
        self.setting.addAction(self.actionStyle)
        self.about.addAction(self.actionAbout)
        self.serach.addAction(self.actionBaidu)
        self.menuBar.addAction(self.file.menuAction())
        self.menuBar.addAction(self.edit.menuAction())
        self.menuBar.addAction(self.window.menuAction())
        self.menuBar.addAction(self.setting.menuAction())
        self.menuBar.addAction(self.about.menuAction())
        self.menuBar.addAction(self.serach.menuAction())
        self.toolBar.addAction(self.actionData_Update)
        self.toolBar.addAction(self.actionDatabase_Download)
        self.toolBar.addAction(self.actionAddRow)
        self.toolBar.addAction(self.actionDeleteRow)
        self.toolBar.addAction(self.actionBack)
        self.toolBar.addAction(self.actionGo)
        self.toolBar.addAction(self.actionMagnifying)
        self.toolBar.addAction(self.actionReduce)
        self.toolBar.addAction(self.actionWarning_Black)
        self.toolBar.addAction(self.actionWarning_Red)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHome)
        self.toolBar_user.addAction(self.actionDoctor)
        self.toolBar_user.addAction(self.actionPatient)
        self.toolBar_user.addSeparator()

        self.retranslateUi(OXY)
        QtCore.QMetaObject.connectSlotsByName(OXY)

    def retranslateUi(self, OXY):
        _translate = QtCore.QCoreApplication.translate
        OXY.setWindowTitle(_translate("OXY", "MainWindow"))
        self.groupBox.setTitle(_translate("OXY", "原始图像"))
        self.groupBox_2.setTitle(_translate("OXY", "结果图像"))
        self.comboBox.setItemText(0, _translate("OXY", "关键字"))
        self.comboBox.setItemText(1, _translate("OXY", "姓名"))
        self.comboBox.setItemText(2, _translate("OXY", "年龄"))
        self.comboBox.setItemText(3, _translate("OXY", "住院ID"))
        self.comboBox.setItemText(4, _translate("OXY", "性别"))
        self.comboBox.setItemText(5, _translate("OXY", "主治医生"))
        self.comboBox.setItemText(6, _translate("OXY", "眼底医生"))
        self.comboBox.setItemText(7, _translate("OXY", "创建时间"))
        self.comboBox.setItemText(8, _translate("OXY", "手机号"))
        self.pushButton.setText(_translate("OXY", "搜索"))
        self.comboBox_name.setItemText(0, _translate("OXY", "姓名"))
        self.comboBox_name.setItemText(1, _translate("OXY", "A-Z"))
        self.comboBox_name.setItemText(2, _translate("OXY", "Z-A"))
        self.comboBox_sex.setItemText(0, _translate("OXY", "性别"))
        self.comboBox_sex.setItemText(1, _translate("OXY", "男"))
        self.comboBox_sex.setItemText(2, _translate("OXY", "女"))
        self.comboBox_age.setItemText(0, _translate("OXY", "年龄"))
        self.comboBox_age.setItemText(1, _translate("OXY", "从小到大"))
        self.comboBox_age.setItemText(2, _translate("OXY", "从大到小"))
        self.comboBox_hosID.setItemText(0, _translate("OXY", "住院ID"))
        self.comboBox_hosID.setItemText(1, _translate("OXY", "从小到大"))
        self.comboBox_hosID.setItemText(2, _translate("OXY", "从大到小"))
        self.comboBox_docMain.setItemText(0, _translate("OXY", "主治医生"))
        self.comboBox_docMain.setItemText(1, _translate("OXY", "张一"))
        self.comboBox_docMain.setItemText(2, _translate("OXY", "张二"))
        self.comboBox_docMain.setItemText(3, _translate("OXY", "张三"))
        self.comboBox_id_2.setItemText(0, _translate("OXY", "创建时间"))
        self.comboBox_id_2.setItemText(1, _translate("OXY", "从小到大"))
        self.comboBox_id_2.setItemText(2, _translate("OXY", "从大到小"))
        self.comboBox_docMain_2.setItemText(0, _translate("OXY", "眼底医生"))
        self.comboBox_docMain_2.setItemText(1, _translate("OXY", "李一"))
        self.comboBox_docMain_2.setItemText(2, _translate("OXY", "李二"))
        self.comboBox_docMain_2.setItemText(3, _translate("OXY", "李三"))
        self.pushButton_2.setText(_translate("OXY", "排序"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("OXY", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("OXY", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("OXY", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("OXY", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("OXY", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("OXY", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("OXY", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("OXY", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("OXY", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("OXY", "10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("OXY", "11"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("OXY", "12"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("OXY", "13"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("OXY", "15"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("OXY", "姓名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("OXY", "性别"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("OXY", "年龄"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("OXY", "主治医生"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("OXY", "眼底医生"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("OXY", "住院ID"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("OXY", "会诊记录"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("OXY", "创建时间"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.file.setTitle(_translate("OXY", "文件"))
        self.edit.setTitle(_translate("OXY", "编辑"))
        self.window.setTitle(_translate("OXY", "窗口"))
        self.setting.setTitle(_translate("OXY", "设置"))
        self.about.setTitle(_translate("OXY", "帮助"))
        self.serach.setTitle(_translate("OXY", "搜索"))
        self.toolBar.setWindowTitle(_translate("OXY", "toolBar"))
        self.toolBar_user.setWindowTitle(_translate("OXY", "toolBar_2"))
        self.actionNew.setText(_translate("OXY", "新建"))
        self.actionImage.setText(_translate("OXY", "图像"))
        self.actionImage.setToolTip(_translate("OXY", "image"))
        self.actionnew_Window.setText(_translate("OXY", "新建窗口"))
        self.actionnew_Window.setToolTip(_translate("OXY", "new_Window"))
        self.actionFont.setText(_translate("OXY", "字体"))
        self.actionFont.setToolTip(_translate("OXY", "font"))
        self.actionStyle.setText(_translate("OXY", "风格"))
        self.actionOpen.setText(_translate("OXY", "打开"))
        self.actionSave.setText(_translate("OXY", "保存"))
        self.actionBaidu.setText(_translate("OXY", "百度"))
        self.actionAbout.setText(_translate("OXY", "关于"))
        self.actionData_Update.setText(_translate("OXY", "database_Update"))
        self.actionData_Update.setToolTip(_translate("OXY", "database_Update"))
        self.actionMagnifying.setText(_translate("OXY", "magnifying"))
        self.actionMagnifying.setToolTip(_translate("OXY", "magnifying"))
        self.actionReduce.setText(_translate("OXY", "reduce"))
        self.actionReduce.setToolTip(_translate("OXY", "reduce"))
        self.actionDatabase_Download.setText(_translate("OXY", "database_Download"))
        self.actionDatabase_Download.setToolTip(_translate("OXY", "database_Download"))
        self.actionWarning_Black.setText(_translate("OXY", "warning_Black"))
        self.actionWarning_Black.setToolTip(_translate("OXY", "warning_Black"))
        self.actionWarning_Red.setText(_translate("OXY", "warning_Red"))
        self.actionWarning_Red.setToolTip(_translate("OXY", "warning_Red"))
        self.actionBack.setText(_translate("OXY", "back"))
        self.actionBack.setToolTip(_translate("OXY", "back"))
        self.actionGo.setText(_translate("OXY", "go"))
        self.actionGo.setToolTip(_translate("OXY", "go"))
        self.actionPatient.setText(_translate("OXY", "patient"))
        self.actionPatient.setToolTip(_translate("OXY", "patient"))
        self.actionDoctor.setText(_translate("OXY", "doctor"))
        self.actionDoctor.setToolTip(_translate("OXY", "doctor"))
        self.actionAddRow.setText(_translate("OXY", "addRow"))
        self.actionAddRow.setToolTip(_translate("OXY", "addRow"))
        self.actionDeleteRow.setText(_translate("OXY", "deleteRow"))
        self.actionHome.setText(_translate("OXY", "home"))
        self.actionHome.setToolTip(_translate("OXY", "home"))
        self.actionMianIcon.setText(_translate("OXY", "mianIcon"))
        self.actionMianIcon.setToolTip(_translate("OXY", "mianicon"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OXY = QtWidgets.QMainWindow()
    ui = Ui_OXY()
    ui.setupUi(OXY)
    OXY.show()
    sys.exit(app.exec_())