# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DoctorInfo.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DoctorInfo(object):
    def setupUi(self, DoctorInfo):
        DoctorInfo.setObjectName("DoctorInfo")
        DoctorInfo.resize(640, 451)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/doctor.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DoctorInfo.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(DoctorInfo)
        self.centralwidget.setObjectName("centralwidget")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(0, 0, 631, 371))
        self.treeView.setObjectName("treeView")
        DoctorInfo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DoctorInfo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 23))
        self.menubar.setObjectName("menubar")
        self.file = QtWidgets.QMenu(self.menubar)
        self.file.setObjectName("file")
        self.menu = QtWidgets.QMenu(self.file)
        self.menu.setObjectName("menu")
        DoctorInfo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DoctorInfo)
        self.statusbar.setObjectName("statusbar")
        DoctorInfo.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(DoctorInfo)
        self.toolBar.setObjectName("toolBar")
        DoctorInfo.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(DoctorInfo)
        self.toolBar_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.toolBar_2.setObjectName("toolBar_2")
        DoctorInfo.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionUp_fie = QtWidgets.QAction(DoctorInfo)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/up_file.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUp_fie.setIcon(icon1)
        self.actionUp_fie.setObjectName("actionUp_fie")
        self.actionDown_file = QtWidgets.QAction(DoctorInfo)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/download_file.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDown_file.setIcon(icon2)
        self.actionDown_file.setObjectName("actionDown_file")
        self.actionDelete_Row = QtWidgets.QAction(DoctorInfo)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/deleteRow.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete_Row.setIcon(icon3)
        self.actionDelete_Row.setObjectName("actionDelete_Row")
        self.actionAddRow = QtWidgets.QAction(DoctorInfo)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/addRow.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddRow.setIcon(icon4)
        self.actionAddRow.setObjectName("actionAddRow")
        self.actionDoctor = QtWidgets.QAction(DoctorInfo)
        self.actionDoctor.setIcon(icon)
        self.actionDoctor.setObjectName("actionDoctor")
        self.actionQuit = QtWidgets.QAction(DoctorInfo)
        self.actionQuit.setObjectName("actionQuit")
        self.action_expoExc = QtWidgets.QAction(DoctorInfo)
        self.action_expoExc.setObjectName("action_expoExc")
        self.action_expoTxt = QtWidgets.QAction(DoctorInfo)
        self.action_expoTxt.setObjectName("action_expoTxt")
        self.menu.addAction(self.action_expoExc)
        self.menu.addAction(self.action_expoTxt)
        self.file.addAction(self.menu.menuAction())
        self.file.addAction(self.actionQuit)
        self.menubar.addAction(self.file.menuAction())
        self.toolBar.addAction(self.actionAddRow)
        self.toolBar.addAction(self.actionDelete_Row)
        self.toolBar.addAction(self.actionUp_fie)
        self.toolBar.addAction(self.actionDown_file)
        self.toolBar_2.addAction(self.actionDoctor)
        self.toolBar_2.addSeparator()

        self.retranslateUi(DoctorInfo)
        QtCore.QMetaObject.connectSlotsByName(DoctorInfo)

    def retranslateUi(self, DoctorInfo):
        _translate = QtCore.QCoreApplication.translate
        DoctorInfo.setWindowTitle(_translate("DoctorInfo", "医生信息"))
        self.file.setTitle(_translate("DoctorInfo", "文件"))
        self.menu.setTitle(_translate("DoctorInfo", "另存为"))
        self.toolBar.setWindowTitle(_translate("DoctorInfo", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("DoctorInfo", "toolBar_2"))
        self.actionUp_fie.setText(_translate("DoctorInfo", "up_fie"))
        self.actionDown_file.setText(_translate("DoctorInfo", "down_file"))
        self.actionDelete_Row.setText(_translate("DoctorInfo", "delete_Row"))
        self.actionAddRow.setText(_translate("DoctorInfo", "addRow"))
        self.actionDoctor.setText(_translate("DoctorInfo", "doctor"))
        self.actionQuit.setText(_translate("DoctorInfo", "退出"))
        self.action_expoExc.setText(_translate("DoctorInfo", "输出为excel"))
        self.action_expoTxt.setText(_translate("DoctorInfo", "输出为txt"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OXY = QtWidgets.QMainWindow()
    ui = Ui_DoctorInfo()
    ui.setupUi(OXY)
    OXY.show()
    sys.exit(app.exec_())

