# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PatientInfo.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(664, 514)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/patient.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(0, 0, 661, 451))
        self.treeView.setObjectName("treeView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 664, 23))
        self.menubar.setObjectName("menubar")
        self.file = QtWidgets.QMenu(self.menubar)
        self.file.setObjectName("file")
        self.menu = QtWidgets.QMenu(self.file)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionAddRow = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/addRow.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddRow.setIcon(icon1)
        self.actionAddRow.setObjectName("actionAddRow")
        self.actionDeleteRow = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/deleteRow.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeleteRow.setIcon(icon2)
        self.actionDeleteRow.setObjectName("actionDeleteRow")
        self.actionPatient = QtWidgets.QAction(MainWindow)
        self.actionPatient.setCheckable(True)
        self.actionPatient.setIcon(icon)
        self.actionPatient.setObjectName("actionPatient")
        self.actionUp_file = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/up_file.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUp_file.setIcon(icon3)
        self.actionUp_file.setObjectName("actionUp_file")
        self.actionDown_file = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/download_file.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDown_file.setIcon(icon4)
        self.actionDown_file.setObjectName("actionDown_file")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionTxt = QtWidgets.QAction(MainWindow)
        self.actionTxt.setObjectName("actionTxt")
        self.menu.addAction(self.actionExport)
        self.menu.addAction(self.actionTxt)
        self.file.addAction(self.menu.menuAction())
        self.file.addAction(self.actionQuit)
        self.menubar.addAction(self.file.menuAction())
        self.toolBar.addAction(self.actionAddRow)
        self.toolBar.addAction(self.actionDeleteRow)
        self.toolBar.addAction(self.actionUp_file)
        self.toolBar.addAction(self.actionDown_file)
        self.toolBar_2.addAction(self.actionPatient)
        self.toolBar_2.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "病人信息显示"))
        self.file.setTitle(_translate("MainWindow", "文件"))
        self.menu.setTitle(_translate("MainWindow", "另存为"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.actionAddRow.setText(_translate("MainWindow", "addRow"))
        self.actionAddRow.setToolTip(_translate("MainWindow", "addRow"))
        self.actionDeleteRow.setText(_translate("MainWindow", "deleteRow"))
        self.actionDeleteRow.setToolTip(_translate("MainWindow", "deleteRow"))
        self.actionPatient.setText(_translate("MainWindow", "Patient"))
        self.actionPatient.setToolTip(_translate("MainWindow", "Patient"))
        self.actionUp_file.setText(_translate("MainWindow", "up_file"))
        self.actionUp_file.setToolTip(_translate("MainWindow", "up_file"))
        self.actionDown_file.setText(_translate("MainWindow", "down_file"))
        self.actionDown_file.setToolTip(_translate("MainWindow", "down_file"))
        self.actionExport.setText(_translate("MainWindow", "输出为excel"))
        self.actionQuit.setText(_translate("MainWindow", "退出"))
        self.actionTxt.setText(_translate("MainWindow", "输出为txt"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OXY = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(OXY)
    OXY.show()
    sys.exit(app.exec_())

